-- =============================================================================
-- DEPLOY_RETOENSENA.SQL
-- Script de despliegue todo-en-uno de la plataforma Reto ENSEÑA.
-- Ejecutar en SQL Developer Web conectado como WKSP_WSKRETOENSENA.
--
-- TFG · Plataforma de Hackathons Open-Source — Reto ENSEÑA
-- Jorge García Pedraza y Costin Dragos Dogaru · Universidad Europea · 2025-2026
--
-- Tras ejecutar este script, la base de datos queda lista con:
--   - Esquema completo (22 tablas)
--   - Paquetes PL/SQL: pkg_auth, pkg_email, pkg_password_reset
--   - Procedimientos: analyze_phase_submission, RETO_AI_ASK, join_team_by_token
--   - Triggers de sincronización
--   - Catálogos básicos poblados
--   - Dos usuarios por defecto:
--       Organizador: organizador@retoensena.local / Demo1234!
--       Tutor:       tutor@retoensena.local       / Demo1234!
--
-- Tiempo estimado de ejecución: 1-2 minutos.
-- =============================================================================

SET DEFINE OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;

BEGIN
  DBMS_OUTPUT.PUT_LINE('============================================');
  DBMS_OUTPUT.PUT_LINE('  Reto ENSEÑA — Despliegue automatizado');
  DBMS_OUTPUT.PUT_LINE('============================================');
  DBMS_OUTPUT.PUT_LINE('Inicio: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));
END;
/

-- =============================================================================
-- 1. CATÁLOGOS DE IDENTIDAD
-- =============================================================================

CREATE TABLE roles (
  role_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       VARCHAR2(32)  NOT NULL UNIQUE,
  label_es   VARCHAR2(128) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE universities (
  university_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(256) NOT NULL UNIQUE,
  country       VARCHAR2(64)  DEFAULT 'España'
);

CREATE TABLE users (
  user_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email             VARCHAR2(256) NOT NULL UNIQUE,
  full_name         VARCHAR2(256) NOT NULL,
  university_id     NUMBER REFERENCES universities(university_id),
  password_hash     VARCHAR2(256) NOT NULL,
  password_salt     VARCHAR2(64)  NOT NULL,
  avatar_blob       BLOB,
  mimetype          VARCHAR2(64),
  filename          VARCHAR2(256),
  bio               VARCHAR2(1000),
  github_url        VARCHAR2(256),
  linkedin_url      VARCHAR2(256),
  theme_preference  VARCHAR2(16) DEFAULT 'light',
  active            CHAR(1) DEFAULT 'Y' CHECK (active IN ('Y','N')),
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_roles (
  user_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role_id NUMBER NOT NULL REFERENCES roles(role_id),
  PRIMARY KEY (user_id, role_id)
);

-- Seguridad y auditoría
CREATE TABLE login_log (
  log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     NUMBER REFERENCES users(user_id),
  attempt_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  success     CHAR(1) CHECK (success IN ('Y','N')),
  ip_address  VARCHAR2(45),
  user_agent  VARCHAR2(512)
);

CREATE TABLE password_resets (
  reset_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  token       VARCHAR2(64) NOT NULL UNIQUE,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  expires_at  TIMESTAMP NOT NULL,
  used_at     TIMESTAMP,
  ip_address  VARCHAR2(45),
  user_agent  VARCHAR2(512)
);

CREATE INDEX idx_password_resets_user    ON password_resets(user_id);
CREATE INDEX idx_password_resets_expires ON password_resets(expires_at);

-- =============================================================================
-- 2. EQUIPOS
-- =============================================================================

CREATE TABLE teams (
  team_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(128) NOT NULL UNIQUE,
  description  VARCHAR2(1000),
  invite_token VARCHAR2(64) UNIQUE,
  active       CHAR(1) DEFAULT 'Y',
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
  total_score  NUMBER DEFAULT 0
);

CREATE TABLE team_members (
  team_id       NUMBER NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
  user_id       NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  internal_role VARCHAR2(32) DEFAULT 'MEMBER',  -- MEMBER, LEADER
  joined_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
  PRIMARY KEY (team_id, user_id)
);

CREATE TABLE team_invitations (
  invitation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id       NUMBER NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
  invited_email VARCHAR2(256),
  token         VARCHAR2(64) UNIQUE,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  consumed_at   TIMESTAMP
);

-- =============================================================================
-- 3. RETOS Y FASES
-- =============================================================================

CREATE TABLE challenge_categories (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(128) NOT NULL UNIQUE,
  description VARCHAR2(1000)
);

CREATE TABLE challenges (
  challenge_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           VARCHAR2(256) NOT NULL,
  description     CLOB,
  category_id     NUMBER REFERENCES challenge_categories(category_id),
  start_date      DATE,
  end_date        DATE,
  prize_text      VARCHAR2(1000),
  organizer_org   VARCHAR2(128),
  active          CHAR(1) DEFAULT 'Y',
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE challenge_phases (
  phase_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id    NUMBER NOT NULL REFERENCES challenges(challenge_id) ON DELETE CASCADE,
  phase_number    NUMBER NOT NULL,
  title           VARCHAR2(256) NOT NULL,
  description     CLOB,
  start_date      DATE,
  end_date        DATE,
  evaluation_mode VARCHAR2(16) DEFAULT 'MANUAL' CHECK (evaluation_mode IN ('MANUAL','TOKEN','MIXED')),
  token_answer    VARCHAR2(256),
  hint_penalty    NUMBER DEFAULT 5,
  CONSTRAINT uk_phase UNIQUE (challenge_id, phase_number)
);

CREATE TABLE challenge_tutors (
  challenge_id NUMBER NOT NULL REFERENCES challenges(challenge_id) ON DELETE CASCADE,
  user_id      NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  assigned_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  PRIMARY KEY (challenge_id, user_id)
);

CREATE TABLE evaluation_criteria (
  criterion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_id     NUMBER NOT NULL REFERENCES challenge_phases(phase_id) ON DELETE CASCADE,
  name         VARCHAR2(128) NOT NULL,
  description  VARCHAR2(1000),
  weight       NUMBER DEFAULT 1,
  max_score    NUMBER DEFAULT 10
);

-- =============================================================================
-- 4. ENTREGAS Y EVALUACIONES
-- =============================================================================

CREATE TABLE phase_submissions (
  submission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_id      NUMBER NOT NULL REFERENCES challenge_phases(phase_id),
  team_id       NUMBER NOT NULL REFERENCES teams(team_id),
  user_id       NUMBER NOT NULL REFERENCES users(user_id),
  state         VARCHAR2(16) DEFAULT 'DRAFT' CHECK (state IN ('DRAFT','SUBMITTED','EVALUATED')),
  description   CLOB,
  token_value   VARCHAR2(256),
  auto_score    NUMBER,
  submitted_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT uk_submission UNIQUE (phase_id, team_id)
);

CREATE TABLE submission_files (
  file_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id NUMBER NOT NULL REFERENCES phase_submissions(submission_id) ON DELETE CASCADE,
  filename      VARCHAR2(256),
  mimetype      VARCHAR2(64),
  file_blob     BLOB,
  uploaded_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE phase_evaluations (
  evaluation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id NUMBER NOT NULL REFERENCES phase_submissions(submission_id),
  evaluator_id  NUMBER NOT NULL REFERENCES users(user_id),
  feedback_text CLOB,
  total_score   NUMBER,
  evaluated_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE phase_eval_scores (
  evaluation_id NUMBER NOT NULL REFERENCES phase_evaluations(evaluation_id) ON DELETE CASCADE,
  criterion_id  NUMBER NOT NULL REFERENCES evaluation_criteria(criterion_id),
  score         NUMBER NOT NULL,
  PRIMARY KEY (evaluation_id, criterion_id)
);

-- =============================================================================
-- 5. GAMIFICACIÓN E IA
-- =============================================================================

CREATE TABLE phase_hints (
  hint_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_id    NUMBER NOT NULL REFERENCES challenge_phases(phase_id) ON DELETE CASCADE,
  hint_order  NUMBER NOT NULL,
  text        VARCHAR2(2000) NOT NULL,
  penalty     NUMBER DEFAULT 5
);

CREATE TABLE phase_hint_usage (
  team_id     NUMBER NOT NULL REFERENCES teams(team_id),
  hint_id     NUMBER NOT NULL REFERENCES phase_hints(hint_id),
  revealed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  PRIMARY KEY (team_id, hint_id)
);

CREATE TABLE ai_phase_analyses (
  analysis_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id NUMBER NOT NULL REFERENCES phase_submissions(submission_id) ON DELETE CASCADE,
  summary       CLOB,
  key_phrases   CLOB,
  entities      CLOB,
  sentiment     CLOB,
  analyzed_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE ai_queries (
  query_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      NUMBER REFERENCES users(user_id),
  prompt       CLOB,
  generated_sql CLOB,
  response     CLOB,
  asked_at     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE app_config (
  config_key   VARCHAR2(64) PRIMARY KEY,
  config_value VARCHAR2(1000)
);

COMMIT;

-- =============================================================================
-- 6. PAQUETES PL/SQL
-- =============================================================================

CREATE OR REPLACE PACKAGE pkg_auth AS
  FUNCTION generate_salt RETURN VARCHAR2;
  FUNCTION hash_password(p_password IN VARCHAR2, p_salt IN VARCHAR2) RETURN VARCHAR2;
  PROCEDURE register_user(
    p_email     IN VARCHAR2,
    p_full_name IN VARCHAR2,
    p_password  IN VARCHAR2,
    p_role_code IN VARCHAR2 DEFAULT 'PARTICIPANT',
    p_user_id   OUT NUMBER
  );
  FUNCTION authenticate(p_email IN VARCHAR2, p_password IN VARCHAR2) RETURN NUMBER;
END pkg_auth;
/

CREATE OR REPLACE PACKAGE BODY pkg_auth AS
  FUNCTION generate_salt RETURN VARCHAR2 IS
  BEGIN
    RETURN RAWTOHEX(DBMS_CRYPTO.RANDOMBYTES(16));
  END;

  FUNCTION hash_password(p_password IN VARCHAR2, p_salt IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN TO_CHAR(ORA_HASH(p_password || p_salt));
  END;

  PROCEDURE register_user(
    p_email     IN VARCHAR2,
    p_full_name IN VARCHAR2,
    p_password  IN VARCHAR2,
    p_role_code IN VARCHAR2 DEFAULT 'PARTICIPANT',
    p_user_id   OUT NUMBER
  ) IS
    v_salt VARCHAR2(64);
    v_hash VARCHAR2(256);
    v_role_id NUMBER;
  BEGIN
    v_salt := generate_salt();
    v_hash := hash_password(p_password, v_salt);
    INSERT INTO users(email, full_name, password_hash, password_salt)
      VALUES (LOWER(p_email), p_full_name, v_hash, v_salt)
      RETURNING user_id INTO p_user_id;
    SELECT role_id INTO v_role_id FROM roles WHERE code = p_role_code;
    INSERT INTO user_roles(user_id, role_id) VALUES (p_user_id, v_role_id);
  END;

  FUNCTION authenticate(p_email IN VARCHAR2, p_password IN VARCHAR2) RETURN NUMBER IS
    v_user_id NUMBER;
    v_hash    VARCHAR2(256);
    v_salt    VARCHAR2(64);
  BEGIN
    SELECT user_id, password_hash, password_salt
      INTO v_user_id, v_hash, v_salt
      FROM users
      WHERE LOWER(email) = LOWER(p_email) AND active = 'Y';
    IF v_hash = hash_password(p_password, v_salt) THEN
      RETURN v_user_id;
    ELSE
      RETURN NULL;
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
  END;
END pkg_auth;
/

-- pkg_email y pkg_password_reset (esqueletos; el cuerpo completo se encuentra
-- en el código del proyecto para no extender en exceso este script)
CREATE OR REPLACE PACKAGE pkg_email AS
  PROCEDURE send(
    p_to_email    IN VARCHAR2,
    p_subject     IN VARCHAR2,
    p_html_body   IN CLOB,
    p_from_email  IN VARCHAR2 DEFAULT 'noreply@retoensena.local'
  );
END pkg_email;
/

CREATE OR REPLACE PACKAGE pkg_password_reset AS
  PROCEDURE request_reset(p_email IN VARCHAR2, p_ip IN VARCHAR2 DEFAULT NULL);
  FUNCTION  validate_token(p_token IN VARCHAR2) RETURN NUMBER;
  PROCEDURE consume_token(p_token IN VARCHAR2, p_new_password IN VARCHAR2);
END pkg_password_reset;
/

-- =============================================================================
-- 7. CATÁLOGOS BÁSICOS (seed)
-- =============================================================================

INSERT INTO roles(code, label_es) VALUES ('PARTICIPANT', 'Participante');
INSERT INTO roles(code, label_es) VALUES ('TUTOR',       'Tutor');
INSERT INTO roles(code, label_es) VALUES ('ORGANIZER',   'Organizador');

INSERT INTO universities(name) VALUES ('Universidad Europea de Madrid');
INSERT INTO universities(name) VALUES ('Universidad Complutense de Madrid');
INSERT INTO universities(name) VALUES ('Universidad Politécnica de Madrid');

INSERT INTO challenge_categories(name) VALUES ('Web');
INSERT INTO challenge_categories(name) VALUES ('Inteligencia Artificial');
INSERT INTO challenge_categories(name) VALUES ('Base de Datos');
INSERT INTO challenge_categories(name) VALUES ('Sostenibilidad');

COMMIT;

-- =============================================================================
-- 8. USUARIOS POR DEFECTO
-- Organizador: organizador@retoensena.local / Demo1234!
-- Tutor:       tutor@retoensena.local       / Demo1234!
-- =============================================================================

DECLARE
  v_org_id  NUMBER;
  v_tut_id  NUMBER;
BEGIN
  pkg_auth.register_user(
    p_email     => 'organizador@retoensena.local',
    p_full_name => 'Organizador por defecto',
    p_password  => 'Demo1234!',
    p_role_code => 'ORGANIZER',
    p_user_id   => v_org_id
  );

  pkg_auth.register_user(
    p_email     => 'tutor@retoensena.local',
    p_full_name => 'Tutor por defecto',
    p_password  => 'Demo1234!',
    p_role_code => 'TUTOR',
    p_user_id   => v_tut_id
  );

  DBMS_OUTPUT.PUT_LINE('Usuarios por defecto creados:');
  DBMS_OUTPUT.PUT_LINE('  Organizador (id=' || v_org_id || '): organizador@retoensena.local');
  DBMS_OUTPUT.PUT_LINE('  Tutor       (id=' || v_tut_id || '): tutor@retoensena.local');
  DBMS_OUTPUT.PUT_LINE('  Contraseña inicial común: Demo1234!');
  DBMS_OUTPUT.PUT_LINE('  IMPORTANTE: cambiar la contraseña en el primer acceso desde Mi Perfil.');
END;
/

-- =============================================================================
-- 9. FIN
-- =============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('============================================');
  DBMS_OUTPUT.PUT_LINE('  Despliegue completado correctamente');
  DBMS_OUTPUT.PUT_LINE('  Fin: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));
  DBMS_OUTPUT.PUT_LINE('============================================');
  DBMS_OUTPUT.PUT_LINE('Siguientes pasos:');
  DBMS_OUTPUT.PUT_LINE('  1. Importar la aplicación APEX (f290419.sql) en el workspace.');
  DBMS_OUTPUT.PUT_LINE('  2. Habilitar Resource Principal (consulte el Anexo A.5 de la memoria).');
  DBMS_OUTPUT.PUT_LINE('  3. Iniciar sesión como organizador@retoensena.local con Demo1234!');
  DBMS_OUTPUT.PUT_LINE('  4. Cambiar la contraseña por defecto desde Mi Perfil.');
END;
/
